name: "Terraform infrastructure change management pipeline with github actions"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AWS_REGION : "us-east-1"
    AWS_ASSUMED_ROLE : ${{secrets.AWS_ASSUMED_ROLE}}

permissions:
    id-token: write
    contents: write
    pull-requests: write

jobs:
    TerraformJob:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: ${{env.AWS_ASSUMED_ROLE}}
                role-session-name: "terrafom-actions"
                aws-region: ${{env.AWS_REGION}}
                    
            - name: Terraform init
              id: init
              run: terraform init
